### ISSUE TITLE
Markov-tests.callGenerateMLM failing intermittently

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita4j#81]
please compare to js version

**Comment by dhowe** [comment]
```
org.opentest4j.AssertionFailedError: Got 'I claimed that I had a date even better than his if I wanted to .'

But 'a date even better than his if I wanted to.' was found in input:

One reason people lie is to achieve personal power. Achieving personal power is helpful for one who pretends to be more confident than he really is. For example, one of my friends threw a party at his house last month. He asked me to come to his party and bring a date. However, I did not have a girlfriend. One of my other friends, who had a date to go to the party with, asked me about my date. I did not want to be embarrassed, so I claimed that I had a lot of work to do. I said I could easily find a date even better than his if I wanted to. I also told him that his date was ugly. I achieved power to help me feel confident; however, I embarrassed my friend and his date. Although this lie helped me at the time, since then it has made me look down on myself.

[<s>, One, reason, people, lie, is, to, achieve, personal, power, ., </s>, <s>, Achieving, personal, power, is, helpful, for, one, who, pretends, to, be, more, confident, than, he, really, is, ., </s>, <s>, For, example, ,, one, of, my, friends, threw, a, party, at, his, house, last, month, ., </s>, <s>, He, asked, me, to, come, to, his, party, and, bring, a, date, ., </s>, <s>, However, ,, I, did, not, have, a, girlfriend, ., </s>, <s>, One, of, my, other, friends, ,, who, had, a, date, to, go, to, the, party, with, ,, asked, me, about, my, date, ., </s>, <s>, I, did, not, want, to, be, embarrassed, ,, so, I, claimed, that, I, had, a, lot, of, work, to, do, ., </s>, <s>, I, said, I, could, easily, find, a, date, even, better, than, his, if, I, wanted, to, ., </s>, <s>, I, also, told, him, that, his, date, was, ugly, ., </s>, <s>, I, achieved, power, to, help, me, feel, confident, ;, however, ,, I, embarrassed, my, friend, and, his, date, ., </s>, <s>, Although, this, lie, helped, me, at, the, time, ,, since, then, it, has, made, me, look, down, on, myself, ., </s>, <s>, One, reason, people, are, dishonest, is, to, achieve, power, ., </s>] ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:193)
	at rita.test.MarkovTests.callGenerateMLM(MarkovTests.java:367)
```

**Comment by Real-John-Cheung** [comment]
this bug occasionally appear
the code related to mlm seems to be the same in Java and js

looking into isSubArraylist() (the use of 'OUT:' seems to be strange and not necessary) and validateMlm()

**Comment by dhowe** [comment]
then make isSubArraylist public and write some tests (in markov-tests) to check that it is correct

**Comment by dhowe** [comment]
this is high priority as it it (I think) the lat bug pre-publishing v2.0
